import type { Core } from '@strapi/strapi';
import { aiEnabled } from './ai';

/**
 * Every-minute cron. AI enabled: analyze pending/failed (+ previously skipped —
 * auto-catch-up after a key is added). AI disabled: mark pending as 'skipped'
 * and STILL Slack-notify — ingest → queue → respond works fully without AI;
 * labeling is manual. humanCorrected fields are never overwritten.
 */
export const sweep = ({ strapi }: { strapi: Core.Strapi }) => ({
  async run() {
    const notifySlack = () => strapi.service('api::notify.slack') as any;

    if (!aiEnabled()) {
      // Keyless: adopt Octolens sentiment where the raw payload carries it
      // (modelVersion 'octolens'); otherwise mark skipped. Also rescans
      // skipped-but-unlabeled mentions so pre-feature backlogs get labeled.
      const intakeService = strapi.service('api::ingest.intake') as any;
      const pending = await strapi.documents('api::mention.mention').findMany({
        filters: {
          $or: [
            { analysisStatus: 'pending' },
            { analysisStatus: 'skipped', sentimentLabel: { $null: true } },
          ],
        } as any,
        limit: 50,
        sort: 'receivedAt:asc' as any,
      });
      for (const mention of pending) {
        const octolens = intakeService.octolensSentiment(mention.raw);
        if (octolens) {
          const updated = await strapi.documents('api::mention.mention').update({
            documentId: mention.documentId,
            data: {
              analysisStatus: 'analyzed',
              sentimentLabel: octolens.label,
              sentimentScore: octolens.score,
              modelVersion: 'octolens',
              promptVersion: 'label-map-v1',
            } as any,
          });
          await strapi.documents('api::activity.activity').create({
            data: {
              mention: mention.documentId,
              action: 'analyzed',
              detail: { modelVersion: 'octolens', label: octolens.label },
              at: new Date().toISOString(),
            } as any,
          });
          if (mention.analysisStatus === 'pending') {
            await notifySlack().newMention(updated).catch(() => {});
          }
        } else if (mention.analysisStatus === 'pending') {
          const updated = await strapi.documents('api::mention.mention').update({
            documentId: mention.documentId,
            data: { analysisStatus: 'skipped' } as any,
          });
          await notifySlack().newMention(updated).catch(() => {});
        }
      }
      return pending.length;
    }

    const pending = await strapi.documents('api::mention.mention').findMany({
      filters: { analysisStatus: { $in: ['pending', 'failed', 'skipped'] } },
      populate: { topics: true } as any,
      limit: 20,
      sort: 'receivedAt:asc' as any,
    });
    for (const mention of pending) {
      try {
        const result = await (strapi.service('api::analysis.ai') as any).analyze(mention);
        if (!result) continue; // key removed mid-sweep

        // ensure topics exist (slug auto-generated by the Document Service middleware)
        const topicIds: string[] = [];
        for (const name of result.topics) {
          let topic = await strapi.documents('api::topic.topic').findFirst({ filters: { name } });
          if (!topic) topic = await strapi.documents('api::topic.topic').create({ data: { name } as any });
          topicIds.push(topic.documentId);
        }

        // humanCorrected fields are never overwritten (spec rule)
        const data: any = mention.humanCorrected
          ? { analysisStatus: 'analyzed', modelVersion: result.modelVersion, promptVersion: result.promptVersion }
          : {
              analysisStatus: 'analyzed',
              sentimentScore: result.score,
              sentimentLabel: result.label,
              topics: topicIds,
              modelVersion: result.modelVersion,
              promptVersion: result.promptVersion,
            };
        const updated = await strapi
          .documents('api::mention.mention')
          .update({ documentId: mention.documentId, data });

        await strapi.documents('api::activity.activity').create({
          data: {
            mention: mention.documentId,
            action: 'analyzed',
            detail: { modelVersion: result.modelVersion, label: result.label },
            at: new Date().toISOString(),
          } as any,
        });
        if (mention.analysisStatus === 'pending') {
          await notifySlack().newMention(updated).catch(() => {});
        }
      } catch (err: any) {
        strapi.log.error(`[analysis] sweep failed for ${mention.documentId}: ${err.message}`);
        await strapi
          .documents('api::mention.mention')
          .update({ documentId: mention.documentId, data: { analysisStatus: 'failed' } as any })
          .catch(() => {});
        await notifySlack()
          .ops(`analysis failed for mention ${mention.documentId}: ${err.message}`)
          .catch(() => {});
      }
    }
    return pending.length;
  },

  /** Nightly: re-queue analyzed-but-topicless mentions (never touches humanCorrected). No-op when AI disabled or budget exhausted. */
  async recluster() {
    if (!aiEnabled()) return 0;
    const { exceeded } = await (strapi.service('api::analysis.budget') as any).status();
    if (exceeded) {
      strapi.log.warn('[analysis] recluster skipped — daily AI budget exhausted');
      return 0;
    }
    const orphans = await strapi.documents('api::mention.mention').findMany({
      filters: { analysisStatus: 'analyzed', humanCorrected: false, topics: { documentId: { $null: true } } } as any,
      limit: 50,
    });
    for (const mention of orphans) {
      await strapi
        .documents('api::mention.mention')
        .update({ documentId: mention.documentId, data: { analysisStatus: 'pending' } as any });
    }
    return orphans.length;
  },
});

export default sweep;
