import type { Core } from '@strapi/strapi';
import { aiEnabled } from './ai';

/**
 * Every-minute cron. AI enabled: analyze pending/failed (+ previously skipped —
 * auto-catch-up after a key is added). AI disabled: mark pending as 'skipped'
 * and STILL Slack-notify — ingest → queue → respond works fully without AI;
 * labeling is manual. humanCorrected fields are never overwritten.
 */

/** overlap guard: 20 sequential AI calls easily exceed the 60s cron cadence —
 *  overlapping runs double AI spend and duplicate activities/notifications
 *  (same race the octolens sync service guards against). */
let sweepRunning = false;

/** failed mentions are retried at most this many times, then parked with ONE
 *  ops alert — otherwise a permanently-failing mention (or a globally bad AI
 *  key) starves the queue and pings ops every minute forever. */
const MAX_ATTEMPTS = 5;

/** Slack-notify only for fresh mentions — backfills of old content must not
 *  flood the team channel (same gate as the octolens intake). */
const NOTIFY_FRESHNESS_MS = 6 * 3600_000;
const isFresh = (m: any) =>
  Date.now() - new Date(m.postedAt ?? m.receivedAt ?? Date.now()).getTime() <= NOTIFY_FRESHNESS_MS;

export const sweep = ({ strapi }: { strapi: Core.Strapi }) => ({
  async run() {
    if (sweepRunning) {
      strapi.log.info('[analysis] sweep skipped — previous run still in progress');
      return 0;
    }
    sweepRunning = true;
    try {
      return await this.runSweep();
    } finally {
      sweepRunning = false;
    }
  },

  async runSweep() {
    const notifySlack = () => strapi.service('api::notify.slack') as any;

    if (!aiEnabled()) {
      // Keyless: adopt Octolens sentiment where the raw payload carries it
      // (modelVersion 'octolens'); otherwise mark skipped. Also rescans
      // skipped-but-unlabeled mentions so pre-feature backlogs get labeled.
      const intakeService = strapi.plugin('octolens').service('intake') as any;
      const pending = await strapi.documents('api::mention.mention').findMany({
        filters: {
          $or: [
            { analysisStatus: 'pending' },
            { analysisStatus: 'skipped', sentimentLabel: { $null: true } },
          ],
        } as any,
        limit: 50,
        sort: 'receivedAt:asc' as any,
      });
      for (const mention of pending) {
        const octolens = intakeService.octolensSentiment(mention.raw);
        if (octolens) {
          const updated = await strapi.documents('api::mention.mention').update({
            documentId: mention.documentId,
            data: {
              analysisStatus: 'analyzed',
              sentimentLabel: octolens.label,
              sentimentScore: octolens.score,
              modelVersion: 'octolens',
              promptVersion: 'label-map-v1',
            } as any,
          });
          await strapi.documents('api::activity.activity').create({
            data: {
              mention: mention.documentId,
              action: 'analyzed',
              detail: { modelVersion: 'octolens', label: octolens.label },
              at: new Date().toISOString(),
            } as any,
          });
          if (mention.analysisStatus === 'pending' && isFresh(mention)) {
            await notifySlack().newMention(updated).catch(() => {});
          }
        } else if (mention.analysisStatus === 'pending') {
          const updated = await strapi.documents('api::mention.mention').update({
            documentId: mention.documentId,
            data: { analysisStatus: 'skipped' } as any,
          });
          if (isFresh(mention)) await notifySlack().newMention(updated).catch(() => {});
        }
      }
      return pending.length;
    }

    const pending = await strapi.documents('api::mention.mention').findMany({
      filters: {
        $or: [
          { analysisStatus: { $in: ['pending', 'skipped'] } },
          // failed: retry only until the attempt cap; parked rows leave the window
          {
            analysisStatus: 'failed',
            $or: [{ analysisAttempts: { $lt: MAX_ATTEMPTS } }, { analysisAttempts: { $null: true } }],
          },
        ],
      } as any,
      populate: { topics: true } as any,
      limit: 20,
      sort: 'receivedAt:asc' as any,
    });
    for (const mention of pending) {
      try {
        const result = await (strapi.service('api::analysis.ai') as any).analyze(mention);
        if (!result) continue; // key removed mid-sweep

        // ensure topics exist (slug auto-generated by the Document Service middleware)
        const topicIds: string[] = [];
        for (const name of result.topics) {
          let topic = await strapi.documents('api::topic.topic').findFirst({ filters: { name } });
          if (!topic) topic = await strapi.documents('api::topic.topic').create({ data: { name } as any });
          topicIds.push(topic.documentId);
        }

        // humanCorrected fields are never overwritten (spec rule)
        const data: any = mention.humanCorrected
          ? { analysisStatus: 'analyzed', analysisAttempts: 0, modelVersion: result.modelVersion, promptVersion: result.promptVersion }
          : {
              analysisStatus: 'analyzed',
              analysisAttempts: 0,
              sentimentScore: result.score,
              sentimentLabel: result.label,
              topics: topicIds,
              modelVersion: result.modelVersion,
              promptVersion: result.promptVersion,
            };
        const updated = await strapi
          .documents('api::mention.mention')
          .update({ documentId: mention.documentId, data });

        await strapi.documents('api::activity.activity').create({
          data: {
            mention: mention.documentId,
            action: 'analyzed',
            detail: { modelVersion: result.modelVersion, label: result.label },
            at: new Date().toISOString(),
          } as any,
        });
        if (mention.analysisStatus === 'pending' && isFresh(mention)) {
          await notifySlack().newMention(updated).catch(() => {});
        }
      } catch (err: any) {
        const attempts = ((mention as any).analysisAttempts ?? 0) + 1;
        const parked = attempts >= MAX_ATTEMPTS;
        strapi.log.error(
          `[analysis] sweep failed for ${mention.documentId} (attempt ${attempts}/${MAX_ATTEMPTS}): ${err.message}`
        );
        await strapi
          .documents('api::mention.mention')
          .update({
            documentId: mention.documentId,
            data: { analysisStatus: 'failed', analysisAttempts: attempts } as any,
          })
          .catch(() => {});
        // ONE ops alert when a mention parks — not one per minute forever
        if (parked) {
          await notifySlack()
            .ops(
              `analysis PARKED for mention ${mention.documentId} after ${attempts} attempts: ${err.message} — fix the cause, then use replay to re-queue`
            )
            .catch(() => {});
        }
      }
    }
    return pending.length;
  },

  /** Nightly: re-queue analyzed-but-topicless mentions (never touches humanCorrected). No-op when AI disabled or budget exhausted. */
  async recluster() {
    if (!aiEnabled()) return 0;
    const { exceeded } = await (strapi.service('api::analysis.budget') as any).status();
    if (exceeded) {
      strapi.log.warn('[analysis] recluster skipped — daily AI budget exhausted');
      return 0;
    }
    const orphans = await strapi.documents('api::mention.mention').findMany({
      filters: { analysisStatus: 'analyzed', humanCorrected: false, topics: { documentId: { $null: true } } } as any,
      limit: 50,
    });
    for (const mention of orphans) {
      await strapi
        .documents('api::mention.mention')
        .update({ documentId: mention.documentId, data: { analysisStatus: 'pending' } as any });
    }
    return orphans.length;
  },
});

export default sweep;
